version: 0.2

phases:
  install:
    commands:
        - add-apt-repository ppa:deadsnakes/ppa
        - apt-get update
        - apt purge -y python2.7-minimal
        - apt install python3.9 -y
        - apt install python3-pip -y
        - pip3 install --upgrade setuptools pip
        - pip3 install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
